spring:
  application:
    name: CarShopCRM
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
application:
  auth:
    access:
      secret: ${ACCESS_SECRET}
      expiration-time: ${ACCESS_EXPIRATION_TIME}
    refresh:
      secret: ${REFRESH_SECRET}
      expiration-time: ${REFRESH_EXPIRATION_TIME}


